apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: demo
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: 569882069481.dkr.ecr.us-east-1.amazonaws.com/demo:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080